version: '3.8'

services:
  web:
    build: .
    image: fastapi_demo
    container_name: fastapi_demo_web
    command: python main.py
    volumes:
      - /home/wenmingshuo/project/fast_demo/logs:/app/logs:rw
    restart: always
    network_mode: host

