version: '3.8'

services:
  web:
    build: .
    image: fastapi_demo
    container_name: fastapi_demo_web
    command: uvicorn main:app --host 0.0.0.0 --port 9000
    volumes:
      - /home/wenmingshuo/project/logs:/app/logs:rw
    restart: always
    network_mode: host

